// <auto-generated />
using System;
using Infraestructura;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructura.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250827000134_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Entidades.EstadoIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosIncidentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "SOLICITADO"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "EN PROCESO"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "RESUELTO"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "CERRADO"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "CANCELADO"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Impacto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImpactosIncidentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "UN USUARIO"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "VARIOS USUARIOS"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "TODA LA INSTITUCIÓN"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdImpacto")
                        .HasColumnType("int");

                    b.Property<int>("IdPrioridad")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Prioridad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PrioridadesIncidentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "NO PUEDE ESPERAR"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "PUEDE ESPERAR UNOS MINUTOS"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "PUEDE ESPERAR HORAS"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "PUEDE ESPERAR DIAS"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.TipoIncidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiposIncidentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "ERROR DE SISTEMA"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "ERROR DE USUARIO"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "CONSULTA SOBRE FUNCIONALIDAD DEL SISTEMA"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "SOLICITUD DE INFORMACIÓN"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "NUEVO REQUERIMIENTO"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
